version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format 'feather'
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  generate_report:
    run: cohort-report:v3.0.0 output/input.feather
    needs: [generate_population]
    config:
      output_path: output/cohort_reports_outputs
    outputs:
      moderately_sensitive:
        reports: output/cohort_reports_outputs/descriptives_input.html
        
  # note not possible to execute and save notebook in a single action with `--execute --to notebook` because of self-dependency
  # still possible to execute and save to html or md file

  summary_html:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/data_summary.ipynb --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400
    needs: [generate_population]
    outputs:
      moderately_sensitive:
        html: output/data_summary.html
